
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 17 13:59:45 SAST 2021
//----------------------------------------------------

package CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CC_EQUALS = 19;
  public static final int IMPORT = 4;
  public static final int INIT = 9;
  public static final int NONASSOC = 25;
  public static final int CODE_STRING = 7;
  public static final int SEMI = 3;
  public static final int STAR = 24;
  public static final int PRECEDENCE = 15;
  public static final int PERCENT_PREC = 21;
  public static final int CODE = 6;
  public static final int COLON = 22;
  public static final int ID = 26;
  public static final int WITH = 10;
  public static final int RIGHT = 17;
  public static final int TERMINAL = 12;
  public static final int COMMA = 14;
  public static final int LEFT = 16;
  public static final int NONTERMINAL = 13;
  public static final int EOF = 0;
  public static final int PARSER = 8;
  public static final int DOT = 23;
  public static final int error = 1;
  public static final int ACTION = 5;
  public static final int START = 18;
  public static final int PACKAGE = 2;
  public static final int BAR = 20;
  public static final int SCAN = 11;
}

